### ISSUE TITLE
Update README with API information and usage

### ISSUE THREAD

**Issue by Lutonite** [heig-lherman/dai-pw04#2]

**Comment by OlinB** [comment]
- [x] The README explains the group composition and roles for each member
- [x] The README explains how to install and configure the server with each step
- [x] The README explains how to deploy, run and access the web application
- [x] The README explains how to configure the DNS zone to access your web application
- [x] The README explains how to build and publish the web application with Docker
- [x] The README explains how to interact with the web application with examples and outputs using curl
